### PR TITLE
Fix PAD Factory Influence calculation, update a few other "latest printing" issues.

### LINKED ISSUE #528: PAD Factory influece not discounted with 3xPAD Campaign (System Update 2021) in deck
I suspect PAD Factory is checking for an old version of PAD Campaign while a deck is being built. It also does not surprise me that no one else has seen this error...

### PR DESCRIPTION
**Pull request by plural**
Fixes #528 

I switched some of this to use card names instead of codes, but a more thorough overhaul would be good, especially for the ext-decklist.js stuff.

### CODE REVIEW

File: web/js/nrdb.js [hunk 1]
```diff
@@ -638,22 +638,22 @@ function get_influence_cost_of_card_in_deck(card) {
         if (Identity.code == "03029" && card.type_code == "program") {
             // The Professor: first program is free
             inf = (card.indeck - 1) * card.faction_cost;
-        } else if (card.code === '10018') {
+        } else if (card.code === 'Mumba Temple') {
```
Comment (francescopellegrini) [inline web/js/nrdb.js]:
```suggestion
        } else if (card.title === 'Mumba Temple') {
```

Right?

Comment (plural) [reply web/js/nrdb.js]: oops!  Yes, indeed.

I *swear* i tested this with temple as well.  Thanks for catching this!
